import { chat } from "../index";
import { pickRandom } from "./util";
const sendMessage = (m: HTMLElement | string) => {
	const elem = m instanceof HTMLElement ? m : document.createElement("p");
	if (!(m instanceof HTMLElement)) elem.innerText = m;
	elem.classList.add("chat-message");
	chat.append(elem);
};
const sendChat = (name: string, message: string) => {
	const p = document.createElement("p");
	p.innerText = `: ${message}`;
	const span = document.createElement("span");
	span.classList.add("chat-name");
	span.innerText = name;
	p.prepend(span);
	sendMessage(p);
};
const names = [
	"Mustant",
	"Prodigier",
	"MikeFromTechSupport",
	"Level100",
	"Haxxor",
	"NotASkid",
	"Ultimate",
	"KingHunter",
	"AlyssaB",
	"BobbyF",
	"Bob",
	"FanciestWoman",
	"SoMuchMoney",
	"BrickEater",
	"PIXI",
	"Mooseeater",
	"tastyman",
	"redfox",
	"scp-696969",
	"OWOWhatsthis",
	"Grandederp",
	"KawaiiTheo",
	"Senjogahara",
	"Th3FooL",
	"GusTn",
	"TheTyrant",
	"GoJeonPa",
	"DJJingYun",
	"Egotesticle",
	"IoveLu",
	"OGNEunJungCho",
	"kevybear",
	"ImJas",
	"Agrorenn",
	"Synxia",
	"DouyuTVForgottt",
	"GrimSamurai",
	"6666666666666",
	"RockleeCtrl",
	"Xode",
	"QQ459680082",
	"KittenAnya",
	"Zakard",
	"MARSIRELIA",
	"WallOfText",
	"SireSnoopy",
	"kelppowder",
	"Hxadecimal",
	"onelaugh",
	"MisoMango",
	"PiggyAzalea",
	"MisterDon",
	"VirginEmperor",
	"suzuXIII",
	"P18GEMEINV",
	"Kurumz",
	"kjin",
	"CcLiuShicC",
	"ExileOfTheBlade",
	"Iambbb",
	"Fubguns",
	"Asutarotto",
	"WhatisLove",
	"Niqhtmarea",
	"L0LWal",
	"JannaFKennedy",
	"Steffypoo",
	"KillerHeedonge",
	"AsianSGpotato",
	"whiteclaw",
	"GATOAmyTorin",
	"lovemyRMB",
	"Frostarix",
	"voyyboy",
	"Melo",
	"RiotZALE",
	"ElvishGleeman",
	"givesyouwiings",
	"LoveIy",
	"Packy",
	"Ntzsmgyu",
	"Susice",
	"Dontqqnubz",
	"mikeshiwuer",
	"Chulss",
	"MASTERDING",
	"Scorpionz",
	"KKOBONG",
	"Veeless",
	"NtzMoon",
	"Leesinwiches",
	"RefuseFate",
	"TP101",
	"ozoss0",
	"SeaShell",
	"Baesed",
	"Foolish",
	"jivhust1",
	"KMadKing",
	"CHRlSS",
	"jbraggs",
	"BeefTacos",
	"Xoqe",
	"Naeim",
	"Aerodactyl",
	"Triett",
	"194IQredditor",
	"Pulzar",
	"Windgelu",
	"Suadero",
	"Zulgor",
	"Senks",
	"cAbstracT",
	"SwagersKing",
	"AkameBestGirl",
	"ThePrimaryEdict",
	"arthasqt",
	"Lobstery",
	"MisterOombadu",
	"TheFriendlyDofu",
	"Oryziaslatipes",
	"ugg1",
	"Flandoor",
	"HawkStandard",
	"wimbis",
	"JimmerFredette",
	"VikingKarots",
	"Sorcerawr",
	"Ciscla",
	"Suffix",
	"MrCow",
	"METALCHOCOB0",
	"Dessias",
	"LevelPerfect",
	"midVox",
	"Junha",
	"Hickus",
	"gamepiong",
	"AirscendoSona",
	"HellooKittie",
	"Jesse",
	"Rainaa",
	"ILoveNASoloQ",
	"Colonelk1",
	"DeTRFZerost",
	"Szmao",
	"TacoKat",
	"1tzJustVictor",
	"HomedogPaws",
	"DioDeSol",
	"PeterBrown",
	"FrannyPack",
	"AbsoluteFridges",
	"TheBiddler",
	"ELMdamemitai",
	"Old",
	"Pavle",
	"nathanielbee",
	"MakiIsuzuSento",
	"nweHuang",
	"EvanRL",
	"yorozu",
	"forgivenbow",
	"alexxisss",
	"Cloverblood",
	"Entities",
	"Believe",
	"Chiruno",
	"Xiaobanma",
	"BestJanna",
	"Neko",
	"TheEyeofHorus",
	"IGotSunshine",
	"Shade20",
	"Sprusse",
	"Imacarebear",
	"Kenleebudouchu",
	"LockDownExec",
	"Chubymonkey",
	"HunterHagen",
	"Applum",
	"DaoKho",
	"MrBlackburn",
	"beatmymeat",
	"BestDota2Sona",
	"chubbiercheeks",
	"KillaKast",
	"Betsujin",
	"TheAmberTeahouse",
	"BellaFlica",
	"ManateeWaffles",
	"Babalew",
	"charmanderu",
	"TooSalty",
	"LotusBoyKiller",
	"Bulgogeeeee",
	"Nerzhu1",
	"Lovelyiris",
	"QuantumFizzics",
	"freakingnoodles",
	"Pdop1",
	"Bakudanx",
	"Martel",
	"DoctorDoom",
	"equalix",
	"CARDCAPTORCARD",
	"Dyad",
	"Papasmuff",
	"TheBroskie",
	"Wadenation",
	"Flyinpiggy",
	"Wingsofdeathx",
	"IamOsiris",
	"ArtThief",
	"LotusEdge",
	"fwii",
	"Kios",
	"Shampu",
	"Nickpappa",
	"Yukari",
	"RayXu",
	"Emeraldancer",
	"TwoPants",
	"EnzoIX",
	"Jacka",
	"Plumber",
	"Skadanton",
	"C9TGleebglarbu",
	"BonQuish",
	"GrimmmmmmmReaper",
	"SmoSmoSmo",
	"MewtMe",
	"Ramzlol",
	"Mruseless",
	"Eitori",
	"S0lipsism",
	"X1337Gm4uLk03rX",
	"lloveOreo",
	"MrChivalry",
	"Oyt",
	"AnVu",
	"RBbabbong",
	"MASTERROSHl",
	"dabestmelon",
	"Potatooooooooooo",
];
const messages = [
	"Wow! It works!",
	"I just got all items!",
	"I'm OP now!",
	"How do I do the hack?",
	"I have 9999999!",
	"So much $$$!",
	"Everything is easy now!",
	"It doesn't work. Wait, now it does!",
	"Ooh! A secret item.",
	"I found a secret pet.",
	"I JUST DEALT 92391932931 DAMAGE!",
	"my friends use this every day and they love it",
	"LOL",
	"XD",
	"brb dinner",
	"brb sleep",
	"brb breakfast",
	"brb lunch",
	"my gf will love this",
	"my bf WILL love thiss",
	"yea",
	"Yes",
	"YEEEEEEESSSSSS",
	"WOW! Finally one that works!",
	"I can imagine this must be annoying for some players",
	"Is this ban secure?",
	"Thanks man I appreciate this.",
	"Cool =)",
	"oh god",
	"Damn",
	"I love this",
	"Never imagined this would work but damn its so simple",
	"saw this on forums pretty impressive",
	"Yo guys dont spam okay?",
	"Anyone playing now?",
	"You think this will be patched any time soon",
	"pretty sure this is saving me a lot of money",
	"thank you for giving me ALL THIS",
	"Saw on stream yo",
	"Today is lucky day",
	"this is the best giveaway because we all have more than a chance",
	"i love it so much",
	"this makes my game more enjoyable i hope",
	"Any idea if this still works tomorrow",
	"thank you all for helping me out bros",
	"ok cool",
	"i see no limits on how much you can get thats so epic",
	"So i can get more and more and nobody cares?",
	"think so man",
	"Likely, but I think one day this will not work anymore",
	"this still works at the moment",
	"i havent seen this before but im impressed with the result!",
	"My boyfriend will freak out :D",
	"nice.",
	"Think so",
	"what you can get here for free?",
	"ok sounds good enough for me bros",
	"Anyone reddit here?",
	"Okay I believe this works cus I just got 1000 which was my test run on my acc ROFL",
	"hope not too many kids in this chat",
	"josh are you here?",
	"unlocking takes some time for me",
	"derp",
	"i am curious is this legit?",
	"Works on all servers?",
	"Had to reload page before it worked",
	"used this three times in a row with 15k lol this is great",
	"i see most people here write positive things it is true?",
	"hi my english no good i here get good free?",
	"Exactly what I think",
	"you can have no IQ and still be able to use this generator",
	"when i came first to this website i was like most of you guys just spamming here the chat, in the end im glad that i tried it because now for next year or so i will not buy anymore",
];
const sendRand = () => sendChat(pickRandom(names), pickRandom(messages));
const interval = () => {
	sendRand();
	if (Math.random() > 0.965) sendChat("Noot", "where is foreskin hack?")
	setTimeout(interval, 1000 + Math.random() * 10000);
	chat.scrollTop = chat.scrollHeight;
};
interval();
